name: Generate site

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get yarn
      run: |
        apt update
        apt install yarn
    - name: Get dependencies
      run: |
         yarn
    - name: Build site
      run: |
        yarn build
